CODES=[("DA1","Unit 3","Data analysis","Types of data (categorical: nominal/ordinal; numerical: discrete/continuous)"),
("DA2","Unit 3","Data analysis","Displays of distributions: frequency tables, bar charts, histograms, stem/dot plots, log (base 10) scales"),
("DA3","Unit 3","Data analysis","Five-number summary, boxplots, outliers"),
("DA4","Unit 3","Data analysis","Mean and standard deviation; normal model, 68–95–99.7% rule, z-scores"),
("DA5","Unit 3","Data analysis","Associations: response/explanatory variables, two-way tables, segmented bar charts, back-to-back stem plots, parallel boxplots, scatterplots"),
("DA6","Unit 3","Data analysis","Correlation coefficient r; correlation vs causation"),
("DA7","Unit 3","Data analysis","Least squares line: equation, interpretation of slope/intercept, predictions, extrapolation, r²"),
("DA8","Unit 3","Data analysis","Residual analysis and data transformations (linearity)"),
("DA9","Unit 3","Data analysis","Time series: features (trend, seasonality, irregular fluctuations, outliers), smoothing"),
("DA10","Unit 3","Data analysis","Seasonal indices (calculate, deseasonalise, reseasonalise)"),
("DA11","Unit 3","Data analysis","Least squares trend lines and forecasting"),
("RF1","Unit 3","Recursion & financial modelling","First-order linear recurrence relations (u_{n+1} = R·u_n + d): generating and interpreting terms"),
("RF2","Unit 3","Recursion & financial modelling","Simple interest; flat rate and unit cost depreciation"),
("RF3","Unit 3","Recursion & financial modelling","Compound interest and reducing balance depreciation; future value rule"),
("RF4","Unit 3","Recursion & financial modelling","Nominal vs effective interest rates"),
("RF5","Unit 3","Recursion & financial modelling","Reducing balance loans and amortisation tables"),
("RF6","Unit 3","Recursion & financial modelling","Annuities and perpetuities"),
("RF7","Unit 3","Recursion & financial modelling","Annuity investments"),
("RF8","Unit 3","Recursion & financial modelling","Finance solver (TVM) use for practical problems"),
("RF9","Unit 3","Recursion & financial modelling","Interest-only loans (balance constant: interest each period = repayment)"),
("MA1","Unit 4","Matrices","Order, types of matrices, transpose, matrix operations (sum, scalar, product, power)"),
("MA2","Unit 4","Matrices","Inverse and determinant; when an inverse exists"),
("MA3","Unit 4","Matrices","Communication and dominance matrices"),
("MA4","Unit 4","Matrices","Transition diagrams ↔ transition matrices; regular transition matrices"),
("MA5","Unit 4","Matrices","Matrix recurrence relations: state matrices, steady state/equilibrium"),
("MA6","Unit 4","Matrices","Populations with culling/restocking (S_{n+1} = T·S_n + B)"),
("MA7","Unit 4","Matrices","Leslie-type (age-structured) population matrices: birth and survival rates from life-cycle diagrams"),
("ND1","Unit 4","Networks & decision maths","Graph terminology, types, degree, isomorphic/connected graphs, adjacency matrices"),
("ND2","Unit 4","Networks & decision maths","Euler's formula and planar graphs"),
("ND3","Unit 4","Networks & decision maths","Walks, trails, paths; Eulerian trails/circuits; Hamiltonian paths/cycles"),
("ND4","Unit 4","Networks & decision maths","Trees, spanning trees, minimum spanning trees, Prim's algorithm"),
("ND5","Unit 4","Networks & decision maths","Flow problems, minimum cut / maximum flow"),
("ND6","Unit 4","Networks & decision maths","Shortest path, Dijkstra's algorithm"),
("ND7","Unit 4","Networks & decision maths","Matching/allocation, Hungarian algorithm"),
("ND8","Unit 4","Networks & decision maths","Scheduling, critical path analysis (EST, LST, float, crashing)")]

# Exam 1 2025: q, answer, %A,%B,%C,%D, code, secondary, task, note
E1=[(1,"D",4,5,17,75,"DA3","DA2","C","Median from a frequency table"),
(2,"D",20,2,1,76,"DA2","","C","Total from a frequency table"),
(3,"D",7,4,7,82,"DA5","DA3","I","Comparing parallel boxplots"),
(4,"D",5,13,30,52,"DA2","","C","Log (base 10) scale"),
(5,"C",6,10,81,3,"DA4","","C","Normal model: find mean and SD from two percentages"),
(6,"C",5,10,79,6,"DA3","","C","Lower fence / outliers"),
(7,"B",2,86,6,6,"DA5","","C","Two-way table percentage"),
(8,"D",9,5,7,79,"DA5","","I","Choosing an appropriate display (segmented bar chart)"),
(9,"A",66,6,23,4,"DA7","","C","Least squares equation from two points on scatterplot"),
(10,"D",22,7,8,63,"DA6","","I","Correlation vs causation"),
(11,"C",5,10,81,4,"DA8","","T","Log transformation, least squares on CAS"),
(12,"C",14,14,61,10,"DA8","DA7","T","Squared transformation then predict"),
(13,"C",10,8,76,5,"DA9","","C","Median smoothing"),
(14,"D",13,1,1,85,"DA9","","I","Describing time series features"),
(15,"B",8,81,6,5,"DA9","","C","Centred moving mean (4-point)"),
(16,"B",8,50,18,23,"DA10","","I","Deseasonalising: % reduction from seasonal index"),
(17,"D",32,6,9,53,"RF2","","K","Simple interest expression"),
(18,"D",14,15,19,52,"RF1","","I","Behaviour of sequence from recurrence (R=0.5, d=0)"),
(19,"B",17,49,25,8,"RF3","RF2","C","Flat rate vs reducing balance depreciation compared"),
(20,"A",55,19,7,18,"RF2","","C","Unit cost depreciation"),
(21,"C",8,16,69,6,"RF6","","C","Perpetuity payments"),
(22,"A",68,13,12,6,"RF7","RF8","T","Annuity investment: find interest rate (finance solver)"),
(23,"B",10,41,17,32,"RF4","RF8","T","Effective → nominal rate, then future value"),
(24,"A",52,16,17,14,"RF6","RF8","T","Annuity with changed payment: find time (finance solver)"),
(25,"A",83,9,5,3,"MA1","","I","Matrix types (binary/permutation)"),
(26,"C",8,3,84,4,"MA1","","C","Element of a matrix product"),
(27,"C",4,6,76,13,"MA2","","C","Determinant = 0 (no inverse)"),
(28,"C",1,4,93,2,"MA3","","I","Communication matrix"),
(29,"A",84,9,5,1,"MA7","MA4","K","Life-cycle (Leslie-type) matrix from diagram"),
(30,"B",10,73,12,5,"MA1","","K","Matrix from element rule f_ij"),
(31,"B",5,70,14,10,"MA1","","I","Which matrix products/sums are defined"),
(32,"B",10,63,6,21,"MA3","","K","Completing a dominance matrix"),
(33,"B",7,76,6,11,"ND3","","C","Counting Hamiltonian cycles"),
(34,"C",8,4,85,3,"ND1","","I","Bridges"),
(35,"B",8,65,15,12,"ND4","","C","Minimum spanning tree length"),
(36,"A",77,12,3,7,"ND5","","C","Capacity of a cut"),
(37,"B",13,73,10,3,"ND5","","C","Maximum flow"),
(38,"A",47,47,4,1,"ND6","","C","Shortest path"),
(39,"B",8,71,11,10,"ND7","","K","Hungarian algorithm steps"),
(40,"C",24,19,39,16,"ND8","","C","Float time with a dummy activity")]

# Exam 2 2025: q, marks, dist(list of % at 0..max), code, sec, task, note
E2=[("1a",1,[16,84],"DA3","","C","Median"),
("1b",1,[23,77],"DA1","","I","Variable type"),
("1c.i",1,[31,69],"DA4","","T","Standard deviation on CAS"),
("1c.ii",1,[53,47],"DA4","DA5","I","Compare spread using SD"),
("1d",1,[11,89],"DA5","","K","Complete percentaged table"),
("2a",1,[15,85],"DA3","","C","Range from boxplot"),
("2b",1,[18,82],"DA3","","C","Upper fence"),
("3",2,[41,13,47],"DA4","","C","z-scores + 68–95–99.7% rule"),
("4a",1,[6,94],"DA5","","I","Identify explanatory variable"),
("4b",1,[79,21],"DA6","","C","r from r² (sign!)"),
("4c",1,[27,73],"DA7","","C","Predict using least squares line"),
("4d",1,[73,27],"DA7","","I","Interpolation vs extrapolation"),
("4e",2,[15,20,65],"DA6","","I","Strength and direction of association"),
("4f.i",1,[59,41],"DA8","","C","Calculate a residual"),
("4f.ii",1,[55,45],"DA8","","K","Plot residual"),
("5a",2,[30,43,28],"DA7","","T","Least squares equation, 4 sig. figs"),
("5b",1,[56,44],"DA7","DA6","I","Interpret coefficient of determination"),
("6a",2,[23,45,32],"DA9","","I","Two qualitative features of time series"),
("6b",2,[74,14,12],"DA10","","C","Calculate a seasonal index"),
("7a",1,[7,93],"RF5","","I","Read amortisation table (amount borrowed)"),
("7b",1,[35,65],"RF5","","I","Why interest decreases"),
("7c",1,[60,40],"RF5","","C","Complete amortisation table row"),
("7d",1,[59,41],"RF5","RF8","T","Number of payments before final payment"),
("8a.i",1,[27,73],"RF2","RF1","K","Recurrence relation: flat rate depreciation"),
("8a.ii",1,[50,50],"RF2","","K","Rule for V_n"),
("8b",1,[31,69],"RF2","","C","Flat rate depreciation percentage"),
("9a",1,[63,37],"RF9","RF1","C","Interest-only loan: weekly interest rate"),
("9b.i",1,[60,40],"RF8","RF5","T","Find annual interest rate (finance solver)"),
("9b.ii",1,[70,30],"RF1","","C","Find R in recurrence relation"),
("10",2,[77,12,11],"RF6","RF1","K","Annuity recurrence relation from halfway point"),
("11a",1,[4,96],"MA1","","C","Order of a matrix"),
("11b",1,[43,57],"MA1","","I","Interpret a matrix product"),
("11c",1,[56,44],"MA1","","K","Construct a diagonal matrix"),
("12a",1,[47,53],"MA5","MA2","C","Previous state matrix (inverse)"),
("12b",1,[87,13],"MA6","","C","Recurrence with additions (S = MS + B)"),
("13a",1,[33,67],"MA4","","I","Meaning of leading diagonal"),
("13b.i",1,[91,9],"MA5","","T","State matrix at week 10 (as %)"),
("13b.ii",2,[77,7,17],"MA5","MA4","C","Number moving G→M in given weeks"),
("14a",1,[35,65],"MA1","","I","Permutation matrix: fixed activities"),
("14b",1,[73,27],"MA1","","C","Apply permutation matrix twice"),
("14c",1,[89,11],"MA1","","I","Interpret P⁴ = I"),
("15a",1,[12,88],"ND1","","C","Sum of degrees"),
("15b",1,[9,91],"ND2","","C","Euler's formula"),
("15c",1,[47,53],"ND3","","I","Name route (Hamiltonian path)"),
("15d",1,[19,81],"ND4","","K","Construct a spanning tree"),
("16",2,[32,48,20],"ND1","","K","Adjacency matrix from map"),
("17a",1,[60,40],"ND3","","I","Why edges must repeat (odd degrees)"),
("17b",1,[73,27],"ND3","","C","Minimum distance with repeated edges"),
("18a",1,[56,44],"ND8","","I","Activities common to critical paths"),
("18b",1,[54,46],"ND8","","C","Latest start time"),
("18c",1,[53,47],"ND8","","C","Longest float"),
("18d",1,[79,21],"ND8","","C","Crashing: minimum additional cost")]
