V={ # id: (title, channel, length)
"aegvEuf2bt4":("Types of data | Year 12 General Maths","MaffsGuru","14:18"),"DUcXZ08IdMo":("Types of Data: Categorical vs Numerical Data","365 Data Science","4:14"),
"VuPcaVbK_AI":("Lesson 9 | Construct Histogram using Log (base 10)","DuxBuddy","11:37"),"wVlZM3CBjyQ":("GM 3&4 Data 1E Log Scale Histograms","H Roberts","9:24"),
"EIz5JMgDNV8":("5 Figure Summary & Box Plots | VCE General Maths 3&4","ATAR Notes","8:59"),"tpToLyZibKM":("The Five Number Summary, Boxplots, and Outliers","Simple Learning Pro","5:37"),
"JIw-TurKMfg":("The normal distribution and the 68–95–99.7% rule | Year 12 General Maths","MaffsGuru","19:43"),"mtbJbDwqWLE":("The Normal Distribution and the 68-95-99.7 Rule","Simple Learning Pro","8:50"),
"8fdgZjhHoiI":("Displaying Bivariate Data | VCE General Maths 3&4","ATAR Notes","11:53"),"U785Y-QI-K8":("Two Way Tables","Corbettmaths","3:42"),
"_Kc-QSqaWcs":("Pearson's correlation coefficient and causality | VCE General Maths","MaffsGuru","13:36"),"-rusr-emp_k":("Determining the value of Pearson's correlation coefficient","MaffsGuru","8:28"),
"PplggM0KtJ8":("Interpreting slope of regression line","Khan Academy","2:57"),"ZouqEtVi0pg":("Interpret the Slope and Y-intercept of the Least Squares Regression Line","The Moening Group","5:12"),
"yIl6uO_t6lM":("Data Transformations | VCE General Maths 3&4","ATAR Notes","3:32"),"tAGaemep1Oc":("Lesson 12 | Residual Plot","DuxBuddy","4:04"),
"5ssB0BRydrk":("Smoothing a time series using moving means | Year 12 General Maths","MaffsGuru","29:30"),"Zwgi9czOm78":("Smoothing a time series plot using moving medians","MaffsGuru","20:01"),
"YZA5wIva2XY":("Seasonal indices: calculating SI and deseasonalising data","Australian Mathematics Curriculum Videos","13:32"),"9aZ7ecIqdqw":("Deseasonalising Data and use of seasonal indices","McClatchey Maths","14:22"),
"kYqqag0y7T8":("Time Series – fitting a trend line and forecasting","Further Maths","6:06"),"IjMbMu5UnTQ":("Time Series | VCE General Maths 3&4","ATAR Notes","13:11"),
"6YDVOzwXJyI":("Sequences and recurrence relations | Year 12 General Maths","MaffsGuru","16:40"),"2evxeCH_k2c":("First Order Linear Recurrence Relations","Simmo's Maths Channel","7:51"),
"1lZZSoJ3NFY":("Lesson 17 | Flat Rate Depreciation","DuxBuddy","9:55"),"Aj8XMSc4J4c":("Unit cost depreciation | General Maths Year 12","Brooke Does Maths","10:23"),
"vE_PS9WBLLk":("Calculating compound interest using a recurrence relation","Joel Speranza Math","7:19"),"QdfVolaX1ww":("Reducing-balance depreciation as a recurrence relation","James Banh","4:18"),
"VallHJ5T-2g":("Interest rates over different time periods and effective interest rates","MaffsGuru","33:06"),"kdZQenxsNLk":("Nominal and effective interest rates","LMKMaths","21:04"),
"cvCny7V2fN8":("Amortisation tables | Year 12 General Maths","MaffsGuru","35:57"),"f1ciX7p_lyg":("Amortisation Table – Reducing Balance Loan","Juddy Productions","14:27"),
"mUVwvw2toXM":("Annuities and Perpetuities","Juddy Productions","15:05"),"72KnOALCRwc":("Perpetuities | Year 12 General Maths","MaffsGuru","18:25"),
"lFtC-1fCOLs":("Annuities | VCE Further Maths","VCE Further Maths","19:42"),"sM8y1TH4dvY":("Using a finance solver to find interest rates, time taken and regular payments","MaffsGuru","19:39"),
"shQ3Xoo6VEg":("Using a finance solver to find the balance and final payment","MaffsGuru","29:20"),
"ZfUM4i8569A":("Interest Only Loans | Year 12 General Maths","MaffsGuru","12:42"),"huDGKdiGMYA":("Interest only loans","LMKMaths","18:06"),
"fR7a7Lgkrk8":("Matrices (VCE General Maths) – in 8 minutes!","VCE Maths with Mr Lim","8:19"),"bvBl0Wr8Ank":("Matrix Arithmetic | VCE General Maths 3&4","ATAR Notes","36:12"),
"NOXCZIZ8Jtg":("Matrices – Finding Determinant & Inverse","The Maths Prof","4:13"),"dNp9eTnl9HI":("Inverse matrices and solving simultaneous equations","MaffsGuru","21:54"),
"I3ZhoHFzz0M":("Communication Matrices | VCE General Maths 3&4","ATAR Notes","8:47"),"i5shHCUOlMA":("Dominance Matrices | VCE General Maths 3&4","ATAR Notes","4:17"),
"tJkc-ZS8uOM":("Transition Matrices | VCE General Maths 3&4","ATAR Notes","11:51"),"MqkrDEO77yI":("Introduction to Transition Matrices","MaffsGuru","5:07"),
"pS1YR2x5mRk":("Using Recursion with Transition Matrices","MaffsGuru","4:46"),
"R63odK_AZAc":("Transition Matrices, Steady State, Culling and Restocking","Johnathon Do","22:46"),"P8UqR0sDMdw":("Transition with restocking and culling","Andy Ng","15:06"),
"sZTcBmLCr-0":("Leslie Matrices | VCE General Maths 3&4","ATAR Notes","6:58"),"I5WM2wdjr1M":("Leslie Matrices for population age distribution modelling","Joel Speranza Math","14:01"),
"HCE3cH9VYfg":("Networks Key Knowledge & Features | VCE General Maths 3&4","ATAR Notes","26:40"),"5S1II7Mc8v8":("Creating an Adjacency Matrix from a network graph","Joel Speranza Math","3:16"),
"z1jSVZ36Ruw":("Planar Graphs – Euler's Formula","Joel Speranza Math","6:48"),"bAVSFX_EIRQ":("Planar graphs and Euler's formula","MaffsGuru","11:32"),
"iVeqKWHFhao":("Eulerian trails and circuits","MaffsGuru","8:55"),"rVwZacNZh34":("Hamiltonian Paths and Cycles","MaffsGuru","7:17"),
"4kkUQWnophk":("Prim's Algorithm for finding minimum spanning trees","Joel Speranza Math","7:40"),"6Qbb1gyPNhk":("Minimum Spanning Trees","MaffsGuru","19:35"),
"rjwwU8dNXug":("Finding maximum flow through a network","Bryn Humberstone","4:59"),"RjX9zUsKaDU":("Maximum flow Minimum Cut","Joel Speranza Math","14:02"),
"g5OV12u3uHY":("Dijkstra's Algorithm (finding shortest path)","Bryn Humberstone","4:21"),"Uv4kkh8rSbU":("Dijkstra's Algorithm | VCE Further Maths","Jesse Osbourne","8:09"),
"BeHp-94C9nI":("Hungarian Algorithm | VCE General Maths 3&4","ATAR Notes","10:31"),"NlH4mw1LYk8":("Hungarian algorithm for minimising AND maximising with CAS","MaffsGuru","10:58"),
"e-Gq9PtTU_Y":("Critical Path Analysis – earliest starting and latest finishing times","Joel Speranza Math","10:28"),"haomlpwRIDw":("Crashing in Activity Networks","Bryn Humberstone","11:16"),
# CAS
"HBS1g3cja2g":("ClassPad: Create a Boxplot from a List","Charlie Watson","2:30"),"329WaMYvs2Y":("TI-Nspire: Mean, Standard Deviation and More","Angie Teaches Math","6:13"),
"lyqGV1cQooE":("General Maths with ClassPad – least squares regression line (data transformation)","Casio Education Australia","3:35"),"Xse7Aqb0fLI":("How to Perform Linear Regression with TI-Nspire","TI Australia","3:42"),
"3OW0dLP_yZE":("General Maths with ClassPad – working with a recurrence relation","Casio Education Australia","1:55"),
"KH2A4h50kWs":("ClassPad: Financial Compound Interest","Charlie Watson","2:50"),"fkIxjYbz4aw":("ClassPad: Financial Loan Repayment","Charlie Watson","3:41"),
"HHb9UhgthEM":("Finance Solver | TI-Nspire CX II CAS","TI Australia","4:16"),
"cJJmwem1B6M":("General Maths with ClassPad – matrix arithmetic","Casio Education Australia","2:16"),"RXjjdyHFlGc":("General Maths with ClassPad – steady state matrix","Casio Education Australia","2:41"),
"Q3sciVuIqOI":("Matrices and operations on the TI-Nspire CX II","Texas Instruments Education","4:54")}
R={"DA1":["aegvEuf2bt4","DUcXZ08IdMo"],"DA2":["wVlZM3CBjyQ","VuPcaVbK_AI"],"DA3":["EIz5JMgDNV8","tpToLyZibKM"],"DA4":["JIw-TurKMfg","mtbJbDwqWLE"],
"DA5":["8fdgZjhHoiI","U785Y-QI-K8"],"DA6":["_Kc-QSqaWcs","-rusr-emp_k"],"DA7":["ZouqEtVi0pg","PplggM0KtJ8"],"DA8":["yIl6uO_t6lM","tAGaemep1Oc"],
"DA9":["5ssB0BRydrk","Zwgi9czOm78"],"DA10":["YZA5wIva2XY","9aZ7ecIqdqw"],"DA11":["kYqqag0y7T8","IjMbMu5UnTQ"],
"RF1":["6YDVOzwXJyI","2evxeCH_k2c"],"RF2":["1lZZSoJ3NFY","Aj8XMSc4J4c"],"RF3":["vE_PS9WBLLk","QdfVolaX1ww"],"RF4":["VallHJ5T-2g","kdZQenxsNLk"],
"RF5":["cvCny7V2fN8","f1ciX7p_lyg"],"RF6":["mUVwvw2toXM","72KnOALCRwc"],"RF7":["lFtC-1fCOLs","sM8y1TH4dvY"],"RF8":["shQ3Xoo6VEg","sM8y1TH4dvY"],"RF9":["ZfUM4i8569A","huDGKdiGMYA"],
"MA1":["fR7a7Lgkrk8","bvBl0Wr8Ank"],"MA2":["NOXCZIZ8Jtg","dNp9eTnl9HI"],"MA3":["I3ZhoHFzz0M","i5shHCUOlMA"],"MA4":["tJkc-ZS8uOM","MqkrDEO77yI"],
"MA5":["tJkc-ZS8uOM","pS1YR2x5mRk"],"MA6":["R63odK_AZAc","P8UqR0sDMdw"],"MA7":["sZTcBmLCr-0","I5WM2wdjr1M"],
"ND1":["HCE3cH9VYfg","5S1II7Mc8v8"],"ND2":["z1jSVZ36Ruw","bAVSFX_EIRQ"],"ND3":["iVeqKWHFhao","rVwZacNZh34"],"ND4":["4kkUQWnophk","6Qbb1gyPNhk"],
"ND5":["rjwwU8dNXug","RjX9zUsKaDU"],"ND6":["g5OV12u3uHY","Uv4kkh8rSbU"],"ND7":["BeHp-94C9nI","NlH4mw1LYk8"],"ND8":["e-Gq9PtTU_Y","haomlpwRIDw"]}
CP={"DA3":"HBS1g3cja2g","DA4":"HBS1g3cja2g","DA6":"lyqGV1cQooE","DA7":"lyqGV1cQooE","DA8":"lyqGV1cQooE","RF1":"3OW0dLP_yZE","RF3":"KH2A4h50kWs","RF4":"KH2A4h50kWs","RF5":"fkIxjYbz4aw","RF6":"fkIxjYbz4aw","RF7":"KH2A4h50kWs","RF8":"fkIxjYbz4aw","RF9":"fkIxjYbz4aw","MA1":"cJJmwem1B6M","MA2":"cJJmwem1B6M","MA3":"cJJmwem1B6M","MA4":"cJJmwem1B6M","MA5":"RXjjdyHFlGc","MA6":"cJJmwem1B6M","MA7":"cJJmwem1B6M"}
TI={"DA3":"329WaMYvs2Y","DA4":"329WaMYvs2Y","DA6":"Xse7Aqb0fLI","DA7":"Xse7Aqb0fLI","DA8":"Xse7Aqb0fLI","RF3":"HHb9UhgthEM","RF4":"HHb9UhgthEM","RF5":"HHb9UhgthEM","RF6":"HHb9UhgthEM","RF7":"HHb9UhgthEM","RF8":"HHb9UhgthEM","RF9":"HHb9UhgthEM","MA1":"Q3sciVuIqOI","MA2":"Q3sciVuIqOI","MA3":"Q3sciVuIqOI","MA4":"Q3sciVuIqOI","MA5":"Q3sciVuIqOI","MA6":"Q3sciVuIqOI","MA7":"Q3sciVuIqOI"}
